### ISSUE TITLE
"Redacted precertificates" link shows 404 error

### ISSUE THREAD

**Issue by rugk** [crtsh/test_websites_monitor#1]
Go to https://crt.sh/?a=1
Click on "Redacted" Precertificates

You get to https://crt.sh/redacted-precertificates and see a 404 error:

> # Not Found
>
>The requested URL /redacted-precertificates was not found on this server.
>
> -----
>Apache Server at crt.sh Port 443

**Comment by robstradling** [comment]
Fixed.  Thanks.
